#!/usr/bin/perl -w

$order="scp ../polyhedral.tar.gz ../polyhedral/manual/manual.pdf quatramaran:SYNC/.";
print $order."\n";
system $order;

$order="ssh quatramaran \"scp SYNC/polyhedral.tar.gz SYNC/manual.pdf dro:public_html/Polyhedral/.\"";
print $order."\n";
system $order;

$order="ssh quatramaran \"/bin/rm SYNC/polyhedral.tar.gz SYNC/manual.pdf\"";
print $order."\n";
system $order;
