#!/usr/bin/perl -w

$order="scp ../polyhedral.tar.gz ../polyhedral/manual/manual.pdf cluster:.";
print $order."\n";
system $order;

$order="ssh cluster \"scp polyhedral.tar.gz manual.pdf dro:public_html/Polyhedral/.\"";
print $order."\n";
system $order;

$order="ssh cluster \"/bin/rm polyhedral.tar.gz manual.pdf\"";
print $order."\n";
system $order;
