#!/usr/bin/perl -w

$File=$ARGV[0];
open(INFILE, $File) or die "Impossible to open ".$File;
@U=<INFILE>;
close(INFILE);


for ($iLine=1; $iLine<=scalar(@U); $iLine++)
{
    $eLine=$U[$iLine-1];
    @C=split("of the minimal", $eLine);
    if (scalar(@C) eq 2)
    {
	$RelLine=$iLine+2;
    }
}
$eLine=$U[$RelLine-1];
@C=split(" ", $eLine);
$nbV=$C[0];


print "return [";
for ($iVert=1; $iVert<=$nbV; $iVert++)
{
    $RelLine=$RelLine+1;
    $eLine=$U[$RelLine-1];
    @C=split(" : ", $eLine);
    @D=split(" ", $C[1]);
    if ($iVert > 1)
    {
	print ",\n";
    }
    print "[";
    for ($iD=1; $iD<=scalar(@D); $iD++)
    {
	if ($iD > 1)
	{
	    print ",";
	}
	print $D[$iD-1];
    }
    print "]";
}
print "];\n";
