#!/usr/bin/perl -w

sub CalcMod($$)
{
    my ($i, $j) = @_;
    my $quot;
    my $res;
    $quot=int($i/$j);
    $res=$i-$quot*$j;
    return $res;
}


$uu=scalar(@ARGV);
if ($uu ne 2)
{
    print "ComputeCoveringDensity is used as\n";
    print "ComputeCoveringDensity [FileInput] [FileOutput]\n";
    die;
}

$FileInput=$ARGV[0];
$FileOutput=$ARGV[1];

open(INFILE, $FileInput) or die "impossible to open ".$FileInput;
@B=<INFILE>;
close(INFILE);
$_=$B[0];
s/\n//;
$TheDim=$_;
#
$_=$B[1];
s/\n//;
$strDet=$_;
#
$_=$B[2];
s/\n//;
$strCov=$_;
#
print "INPUT: dimension=".$TheDim."\n";
print "INPUT: determinant=".$strDet."\n";
print "INPUT: Maximal Square Radius=".$strCov."\n";

@U=split("/", $strCov);
if (scalar(@U) eq 2)
{
    $a=$U[0];
    $b=$U[1];
    $TheCov=$a/$b;
}
else
{
    $TheCov=$strCov;
}

@U=split("/", $strDet);
if (scalar(@U) eq 2)
{
    $a=$U[0];
    $b=$U[1];
    $TheDet=$a/$b;
}
else
{
    $TheDet=$strDet;
}

print "INPUT: square radius as real:".$TheCov."\n";
$TheCovRad=sqrt($TheCov);
$TheDetLattice=sqrt($TheDet);

$val=1;
for ($i=1; $i<=$TheDim; $i++)
{
    $val=$val*$TheCov;
}
$quot=$val/$TheDet;
$red=sqrt($quot);

$pi=3.1415926535;
if (CalcMod($TheDim, 2) eq 0)
{
    $halfd=$TheDim/2;
    $powpi=1;
    $fact=1;
    for ($i=1; $i<=$halfd; $i++)
    {
	$powpi=$powpi*$pi;
	$fact=$fact*$i;
    }
    $VolumeBall=$powpi/$fact;
}
else
{
    $halfd=($TheDim-1)/2;
    $powpi=1;
    for ($i=1; $i<=$halfd; $i++)
    {
	$powpi=$powpi*$pi;
    }
    $fact=1;
    for ($i=0; $i<=$halfd; $i++)
    {
	$fact=$fact*($i+0.5);
    }
    $VolumeBall=$powpi/$fact;
}
print "volume ball=".$VolumeBall."\n";
$CovDens=$red*$VolumeBall;
print "Covering Density sqrt(mu^d/det)=".$red."\n";
print "Covering Density sqrt(mu^d/det) vol(B_d)=".$CovDens."\n";


open(OUT, "> ".$FileOutput);
print OUT "return rec(CovDensityNormalized:=\"".$red."\", CovDensity:=\"".$CovDens."\", CoveringRadius:=\"".$TheCovRad."\", DeterminantLattice:=\"".$TheDetLattice."\");\n";
close(OUT);

