#!/usr/bin/perl -w

$File=$ARGV[0];

open(INFILE, $File);
@RESUL=<INFILE>;
close(INFILE);

$InDeX=0;
while (1)
{
    $line=$RESUL[$InDeX];
    $_=$line;
    s/\n//;
    $line=$_;
    if ($line eq "begin")
    {
	last;
    }
    $InDeX++;
}
$line=$RESUL[$InDeX+1];
if ($line ne "  primal_solution\n")
{
    print "Error in the program\n";
    die;
}
$InDeX++;
@V=();
while(1)
{
    $InDeX++;
    $line=$RESUL[$InDeX];
    if ($line eq "  dual_solution\n")
    {
	last;
    }
    $_=$line;
    s/\n//;
    $line=$_;
    @U=split(":  ", $line);
    $V[scalar(@V)]=$U[1];
}
print "return [1,";
for ($i=1; $i<=scalar(@V); $i++)
{
    print $V[$i-1];
    if ($i<scalar(@V))
    {
	print ",";
    }
}
print "];\n";
