#!/usr/bin/perl -w

@B=<>;
@P1=split(" ", $B[0]);
@P2=split("g", $P1[0]);
$nbMat=$P2[1];

@P1=split(" ", $B[1]);
$dim=$P1[0];

$pos=1;
print "return rec(ListMat:=[\n";
for ($iMat=1; $iMat<=$nbMat; $iMat++)
{
    print "[";
    for ($iLin=1; $iLin<=$dim; $iLin++)
    {
	$pos++;
        print "[";
        @UL=split(" ", $B[$pos]);
        for ($iCol=1; $iCol<=$dim; $iCol++)
        {
            print $UL[$iCol-1];
            if ($iCol<$dim)
            {
                print ",";
            }
        }
        print "]";
        if ($iLin<$dim)
        {
            print ",\n";
        }
    }
    print "]\n";
    $pos++;
    if ($iMat<$nbMat)
    {
	print ",";
    }
    if ($iMat < $nbMat)
    {
	print "\n";
    }
}
print "], order:=";
$_=$B[$pos];
@P1=split(" = ", $B[$pos]);
$chn=$P1[0];
@ssl=split("", $chn);
for ($iCh=1; $iCh<=scalar(@ssl); $iCh++)
{
    $eChar=$ssl[$iCh-1];
    if ($eChar ne " ")
    {
	print $eChar;
    }
}
print ");\n";
