#!/usr/bin/perl -w


$STR=$ARGV[0];
open(IN, $STR);
@B=<IN>;
close(IN);

$line=$B[0];
chomp($line);
print "return \"";
@U=split("", $line);
for ($iChar=1; $iChar<=scalar(@U); $iChar++)
{
    $eChar=$U[$iChar-1];
    if ($eChar eq "\\")
    {
#	print "BONJOUR\n";
	print "\\\\";
    }
    else
    {
	print $eChar;
    }
#    print $eChar;
}
#print $line;
print "\";\n";
