#!/usr/bin/perl -w
use strict;
use warnings;

my $DoWeAdd=0;
my @CanonicalLabel=();
my @ListKeyStop;
$ListKeyStop[0] = "tctotal";
$ListKeyStop[1] = "canupdates";
while(<>)
{
    my $eLine=$_;
    my @W=split(":", $eLine);
    if (scalar(@W) > 1)
    {
	$DoWeAdd=0;
    }
    #
    if ($DoWeAdd eq 1)
    {
	my @CEL=split(" ", $eLine);
	for (my $iVert=1; $iVert<=scalar(@CEL); $iVert++)
	{
	    $CanonicalLabel[scalar(@CanonicalLabel)]=$CEL[$iVert-1];
	}
    }
    #
    my @V=split("=", $eLine);
    my $WeMatch=0;
    for (my $u=0; $u<scalar(@ListKeyStop); $u++)
    {
        if (index($V[0], $ListKeyStop[$u]) != -1)
        {
            $WeMatch=1;
        }
    }
    if ($WeMatch == 1)
    {
	$DoWeAdd=1;
    }
}
print "return [";
for (my $iVert=1; $iVert<=scalar(@CanonicalLabel); $iVert++)
{
    if ($iVert >1)
    {
	print ",";
    }
    print $CanonicalLabel[$iVert-1];
}
print "];\n";
