#!/usr/bin/perl -w


# This script takes the standard entry
# and return the NUDIFIED output

@B=<>;
$len=scalar(@B);

$i=0;
while (1)
{
    if ($i >= $len)
    {
	die;
    }
    if ($B[$i] eq "begin\n")
    {
	last;
    }
    $i++;
}

$j=$i+2;


while (1)
{
    if ($B[$j] eq "end\n")
    {
	last;
    }
    else
    {
	print $B[$j];
    }
    $j++
}


