#!/usr/bin/perl -w


# This script takes the standard entry
# and return the NUDIFIED output

@B=<>;

$i=0;
while (1)
{
    if ($i > scalar(@B))
    {
	print "MAJOR error in NudifyLRS 1\n";
	die;
    }
    if ($B[$i] eq "begin\n")
    {
	last;
    }
    $i++;
}

$j=$i+1;


while (1)
{
    if ($j > scalar(@B))
    {
	print "MAJOR error in NudifyLRS 2\n";
	die;
    }
    if ($B[$j] eq "end\n")
    {
	last;
    }
    else
    {
	print $B[$j];
    }
    $j++
}
