#!/usr/bin/perl -w

$File=$ARGV[0];

open(INFILE, $File);
@RESULT=<INFILE>;
close(INFILE);


$_=$RESULT[0];
s/\n//;
$esl=$_;
@VV=split("/", $esl);
if (scalar(@VV) eq 2)
{
    $fre=$VV[0]/$VV[1];
}
else
{
    $fre=$esl;
}
print "return \"".$fre."\";\n";
