#!/usr/bin/perl -w
use strict;
use warnings;

my $uu=scalar(@ARGV);
if ($uu ne 1)
{
    print "Program is used as\n";
    print "redcheckRead [FileIn]\n";
    print "Where [FileIn] is the output of redcheck\n";
    die;
}

my $File=$ARGV[0];
open(INFILE, $File) or die "Impossible to open ".$File;
my @U=<INFILE>;
close(INFILE);


for (my $iLine=1; $iLine<=scalar(@U); $iLine++)
{
    my $eLine=$U[$iLine-1];
    my @C=split(" ", $eLine);
    my $str=$C[0];
#    $nb=scalar(@C);
#    print "scal=".$nb."\n";
    if (scalar(@C) > 1 && $C[0] eq "Redundant")
    {
	$_=$eLine;
	s/\n//;
	my $fLine=$_;
        my @CKR=split(":", $fLine);
        #
        my $strB=$CKR[1];
	my @CKL=split(" ", $strB);
	print "return [";
	for (my $iEnt=1; $iEnt<=scalar(@CKL); $iEnt++)
	{
	    print $CKL[$iEnt-1];
	    if ($iEnt < scalar(@CKL))
	    {
		print ",";
	    }
	}
	print "];\n";
    }
}
