#!/usr/bin/perl -w

$uu=scalar(@ARGV);
if ($uu ne 1)
{
    print "The program is run as\n";
    print "SmithvalenceToGap [FileIn] > [FileOut]\n";
    die;
}
$eFile=$ARGV[0];

open(INFILE, $eFile) or die "impossible to open ".$eFile;
@B=<INFILE>;
close(INFILE);

$len=scalar(@B);
if ($len < 2)
{
    print "return fail;\n";
}
else
{
    $eLineCrit=$B[$len-2];
    @C=split(" ", $eLineCrit);
    $strRes=$C[0];
    for ($i=2; $i<=scalar(@C); $i++)
    {
	$strRes=$strRes.",".$C[$i-1];
    }
    $strRet="return [".$strRes."];\n";
    print $strRet;
}
