#!/usr/bin/perl -w

$File=$ARGV[0];

open(INFILE, $File) or die "impossible to open file File=".$File;
@RESULT=<INFILE>;
close(INFILE);

print "return ";
print "[";
for ($iC=1; $iC<=scalar(@RESULT); $iC++)
{
    $_=$RESULT[$iC-1];
    s/\n//;
    @line=split(" ", $_);
    print "[";
    for ($iL=1; $iL<=scalar(@line); $iL++)
    {
	print $line[$iL-1];
	if ($iL< scalar(@line))
	{
	    print ",";
	}
    }
    print "]";
    if ($iC<scalar(@RESULT))
    {
	print ",";
    }

}
print "];\n";
