#!/usr/bin/perl -w


# This script takes the standard entry
# and return the NUDIFIED output

@B=<>;

@red=();
@irr=();

$i=0;
while (1)
{
    if ($B[$i] eq "begin\n")
    {
	last;
    }
    $i++;
}

$j=$i+1;


while (1)
{
    if ($B[$j] eq "end\n")
    {
	last;
    }
    else
    {
	@U=split(":", $B[$j]);
	@V=split(" ", $U[0]);
	if ($V[1] eq "e")
	{
	    @irr[scalar(@irr)]=$V[0];
	}
	else
	{
	    @red[scalar(@red)]=$V[0];
#	    print("Bonjour\n");
	}
    }
    $j++
}

print "return [";
for ($i=1; $i<=scalar(@irr); $i++)
{
    if ($i ne 1)
    {
	print ",";
    }
    print $irr[$i-1];
}
print "];\n";
