#!/usr/bin/perl -w
$eProg="ExternalProg/libexact-1.0_mod/libexact_solve";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/libexact-1.0_mod && make && cp solve libexact_solve)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED libexact\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../libexact-1.0_mod/libexact_solve)";
print $order."\n";
if (system($order) != 0) {
    die "Error when symbolic linking\n";
}

exit 0;
