#!/usr/bin/perl -w
use Cwd;
$TheDirPWD = getcwd;

$eProg="ExternalProg/IsomorphismReduction/src/IsomorphismReduction.prog";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $PrefixGMP=$TheDirPWD."/ExternalProg/gmp_install";
    $PrefixLD="LDFLAGS=\"-L".$PrefixGMP."/lib\"";
    $PrefixINC="CPPFLAGS=\"-I".$PrefixGMP."/include\"";
    $order="(cd ExternalProg/IsomorphismReduction ".$PrefixLD." ".$PrefixINC." && ./configure && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Problem during the compilation\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED IsomorphismReduction\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../IsomorphismReduction/src/IsomorphismReduction.prog)";
print $order."\n";
if (system($order) != 0) {
    die "Problem when linking\n";
}

exit 0;
