#!/usr/bin/perl -w
$eProg="ExternalProg/TOPCOM-0.17.8/src/points2triangs";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/TOPCOM-0.17.8 && ./configure && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED topcom\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../TOPCOM-0.17.8/src/points2triangs)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
