#!/usr/bin/perl -w
$eProg="ExternalProg/EnumerationIndependentSet/src/CanonicIndependentFamily";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/EnumerationIndependentSet && ./configure && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling IndependentSet\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED EnumerationIndependentSet\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../EnumerationIndependentSet/src/CanonicIndependentFamily)";
print $order."\n";
if (system($order) != 0) {
    die "Error in linkings\n";
}

exit 0;
