#!/usr/bin/perl -w
$eProg="ExternalProg/VectorSplitting/src/VectorSplitting.prog";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/VectorSplitting && ./configure && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED VectorSplitting\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../VectorSplitting/src/VectorSplitting.prog)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
