#!/usr/bin/perl -w
$eProg="ExternalProg/4ti2-1.6.9/src/zsolve/zsolve";
$test=0;
if (-e $eProg)
{$test=1;}
if ($test eq 0)
{
    $order="(cd ExternalProg/4ti2-1.6.9 && ./configure --disable-groebner && make)";
    print $order."\n";
    if (system($order) != 0) {
	die "Error when compiling\n";
    }
}
if (!(-e $eProg))
{
    print "Compilation of ".$eProg." failed\n";
    exit -1;
}
print "\nCOMPILED zsolve\n\n";

$order="(cd ExternalProg/Binaries && ln -sf ../4ti2-1.6.9/src/zsolve/zsolve)";
print $order."\n";
if (system($order) != 0) {
    die "Error when linking\n";
}

exit 0;
