#!/usr/bin/perl -w

while(<>)
{
    if ($_ ne "\n")
    {
	print "1\n";
	s/\n//;
	@U=split(": ", $_);
	$nbV=$U[1];
	print $nbV."\n";
	$iVert=1;
	while(<>)
	{
	    s/\n//;
	    @V=split(":", $_);
	    @W=split(" ", $V[1]);
	    for ($jVert=1; $jVert<=scalar(@W); $jVert++)
	    {
		if ($jVert>1)
		{
		    print " ";
		}
		print $W[$jVert-1];
	    }
	    print "\n";
	    if ($iVert eq $nbV)
	    {
		last;
	    }
	    $iVert++;
	}
    }
}
print "0\n";
